### ISSUE TITLE
seems doesn't work

### ISSUE THREAD

**Issue by bsns** [imbushuo/EnergyStar#10] opened 2022-07-30 23:45 UTC
![image](https://user-images.githubusercontent.com/8208260/182003692-7100a114-23ad-4db0-927d-d6909ea7ca8c.png)
![image](https://user-images.githubusercontent.com/8208260/182003706-483b6979-0485-4177-bfa6-2a16a1d18e0b.png)
os:AMD Ryzen 7 6800H  win11 21H2

**Comment by imbushuo** [comment] 2022-07-30 23:55
Technically the API exists on 21H2, but only have best result on 22H2. Closing that for now as by design.

**Closed as completed by imbushuo** 2022-07-30 23:55 UTC
